In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
m_list_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np_m_arr_1 = np.array(m_list_1)

In [7]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np_m_arr_1.reshape((1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np_m_arr_1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
np_m_arr_1.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
np_m_arr_1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np_m_arr_1.flatten('F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [16]:
np_m_arr_1.sort(axis=1)

In [17]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np_m_arr_1.sort(axis=0)

In [19]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])